###
POST http://localhost:3001/admin/register
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "password",
}

###
POST http://localhost:3001/agent/register
content-type: application/json

{
    "name": "agent1",
    "email": "agent1@gmail.com",
    "password": "agent1",
    "location": "Dhaka, Dhamrai"
}

