###
POST http://localhost:3009/endorser/register-schema
content-type: application/json

{
    "schemaResult": "{\"_tags\":{\"issuerId\":\"did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi\",\"methodName\":\"indy\",\"schemaId\":\"did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi/anoncreds/v0/SCHEMA/Certificate schema/1.0.4\",\"schemaName\":\"Certificate schema\",\"schemaVersion\":\"1.0.4\",\"unqualifiedSchemaId\":\"LvR6LGmiGzfowBgWtUA5oi:2:Certificate schema:1.0.4\"},\"type\":\"AnonCredsSchemaRecord\",\"metadata\":{\"data\":{}},\"id\":\"0cbca12d-614f-41bb-abbf-21ec831bbab0\",\"schema\":{\"attrNames\":[\"attr1\",\"attr2\"],\"issuerId\":\"did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi\",\"name\":\"Certificate schema\",\"version\":\"1.0.4\"},\"schemaId\":\"did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi/anoncreds/v0/SCHEMA/Certificate schema/1.0.4\",\"methodName\":\"indy\",\"updatedAt\":\"2024-05-23T12:10:14.044Z\"}"
}


###
POST http://localhost:3009/endorser/register-cred-def
content-type: application/json

{
    "credentialDefinition": "{\"_tags\":{\"issuerId\":\"did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi\",\"methodName\":\"indy\",\"credentialDefinitionId\":\"did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi/anoncreds/v0/CredentialDefinition/NationalId/1.0.4\",\"schemaName\":\"Certificate schema\",\"schemaVersion\":\"1.0.4\",\"unqualifiedSchemaId\":\"LvR6LGmiGzfowBgWtUA5oi:2:Certificate schema:1.0.4\"},\"type\":\"AnonCredsSchemaRecord\",\"metadata\":{\"data\":{}},\"id\":\"0cbca12d-614f-41bb-abbf-21ec831bbab0\",\"schema\":{\"attrNames\":[\"attr1\",\"attr2\"],\"issuerId\":\"did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi\",\"name\":\"Certificate schema\",\"version\":\"1.0.4\"},\"credentialDefinitionId\":\"did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi/anoncreds/v0/CredentialDefinition/Certificate schema/1.0.6\",\"methodName\":\"indy\",\"updatedAt\":\"2024-05-23T12:10:14.044Z\"}"
}


###
GET http://localhost:3009/transaction
content-type: application/json

{
    "id": "did:indy:bcovrin:test:LvR6LGmiGzfowBgWtUA5oi/anoncreds/v0/CredentialDefinition/Certificate schema/1.0.6"
}